# This is a basic workflow to help you get started with Actions

name: Release Charts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/release-action

jobs:
  release:
    runs-on: [ self-hosted, bigwave-ubuntu2204-medium-spot-amd64 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0경

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Helm Login
        run: |
          echo ${{ secrets.HARBOR_TOKEN }} | helm registry login ${{ secrets.REGISTRY_URL }} -u r-devops-charts+github-actions --password-stdin

      - name: Chart Release
        env:
          REPO_URL: ${{ secrets.REPO_URL }}
        run: ./release.sh